name: Frontend CI/CD

# main, develop 등 원하시는 브랜치에 맞춰 수정
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      VITE_APP_API_URL: ${{ secrets.VITE_APP_API_URL }}
      VITE_APP_KAKAO_URL: ${{ secrets.VITE_APP_KAKAO_URL }}

    steps:
      # (1) GitHub 레포지토리 checkout
      - name: Check out code
        uses: actions/checkout@v2

      # (2) Node 환경 설정
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 22  # 원하는 버전

      # (3) 의존성 설치
      - name: Install dependencies
        run: yarn install

      # (4) 빌드
      - name: Build
        run: yarn build
        # 빌드 후 dist/ 폴더 생성 (Vite 기본)

      # (5) dist 폴더를 EC2로 전송 (scp-action)
      - name: SCP dist to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_IP }}                # EC2 퍼블릭 IP 혹은 도메인
          username: ubuntu
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}        # PEM 키를 GitHub Secrets에 등록
          source: "dist/**"                             # dist 폴더 안 모든 파일
          target: "/home/ubuntu/frontend/dist"          # 원하는 디렉토리

      # (6) SSH 접속 후 Nginx 재시작(or 원하는 명령)
      - name: SSH reload
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ubuntu
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          envs: VITE_APP_API_URL, VITE_APP_KAKAO_URL
          script_stop: true
          script: |
            echo "Remove old cache files if needed..."
            # rm -rf /home/ubuntu/frontend/dist/*

            echo "Reload Nginx..."
            sudo systemctl reload nginx
